### ISSUE TITLE
short fugitive status

### ISSUE THREAD

**Issue by juanpabloaj** [millermedeiros/vim-statline#1]
A suggestion,  I added this [function](https://github.com/juanpabloaj/dotfiles/blob/master/.vimrc#L337) for fugitive status.

**Comment by millermedeiros** [comment]
someone may have a branch named "M" so renaming "master" to "M" may not be the best option in all cases - I usually work on a "dev" branch and just merge things into "master" before deploy.

I wondered if I should add options to add more items to the begin/end of the status line so people could customize the appearance and show more things without editing the source code...

**Comment by millermedeiros** [comment]
I will ignore it for now but think about an way to add/remove things to the status line. thx.
