### ISSUE TITLE
[bug] statline overlap on scon25

### ISSUE THREAD

**Issue by graudeejs** [millermedeiros/vim-statline#13]
Statline overlap on scon25 (FreeBSD console 80x25). There is plenty of room in middle of statline, that isn't used.

Statline overlap by approx 2 chars.

**Comment by millermedeiros** [comment]
sorry for my ignorance but I have no idea what you are talking about :D

been using it inside MacVim and iTerm2 (OSX) so never seen it overlapping with anything.. any ideas on how to fix it or screenshots? statline only add stuff to the `statusline` so I'm not sure what is causing the problem. thx

**Comment by graudeejs** [comment]
I'll make screenshot... but it'll take few hours before I post it... Need to prepare VirtualBox, install vim etc etc

**Comment by graudeejs** [comment]
I think I know why it overlapped....

FreeBSD console doesn't support UTF-8 yet. And Statline use at least one UTF-8 char (right arrow), for this reason it is displayed in ASCII and thus line length is longer.
