### ISSUE TITLE
Number of selected lines

### ISSUE THREAD

**Issue by graudeejs** [millermedeiros/vim-statline#14]
It would be great (and useful) if statline would display number of selected lines (same way vim does, when statline is disabled)

**Comment by millermedeiros** [comment]
I can still see the number of selected lines if:

``` vim
set laststatus=2   " always display statusline (statline already sets this)
set showcmd        " show partial command on last line of screen.
```

`showcmd` does the trick for me (I'm on OSX)

**Comment by graudeejs** [comment]
Or, right.... I didn't expect it there :D
