### ISSUE TITLE
[request] Add `rbenv` integration

### ISSUE THREAD

**Issue by bjeanes** [millermedeiros/vim-statline#15]
`rbenv` is a light-weight alternative to RVM.

**Comment by millermedeiros** [comment]
can you fork it and add it? just need to duplicate [the RVM code](https://github.com/millermedeiros/vim-statline/blob/7d271ba558/plugin/statline.vim#L106-112)  also add it to the [docs](https://github.com/millermedeiros/vim-statline/blob/7d271ba55820a4becb5028b74f5502b0e3e00641/doc/statline.txt#L41-47) and your name on the contributors (end of docs)..

thx!
