### ISSUE TITLE
Disable colors

### ISSUE THREAD

**Issue by rainerborene** [millermedeiros/vim-statline#18]
How can I disable **all** colors from the status line?

**Comment by millermedeiros** [comment]
To check the existing Syntax highlighting groups and their colors use the command

``` vim
:so $VIMRUNTIME/syntax/hitest.vim
```

then you can `link` the `User1-4` highlight colors to one that has the colors you want or link it to the `StatusLine` group (so it will have the same colors as the `StatusLine`):

``` vim
hi link User1 StatusLine
hi link User2 StatusLine
hi link User3 StatusLine
hi link User4 StatusLine
```

The `StatusLine` and `StatusLineNC` groups usually set the colors with `term=reverse` which means the _foreground color_ will be used as _background color_, you can change the colors like this:

``` vim
" greyscale statusline
hi StatusLine guifg=#000000 guibg=#FFFFFF ctermfg=0 ctermbg=15
hi StatusLineNC guifg=#808080 guibg=#000000 ctermfg=8 ctermbg=0
```

cheers.

**Comment by millermedeiros** [comment]
updated docs with this info: b57028a

``` vim
:help statline-colors
```
