### ISSUE TITLE
Shorten mixed indenting warning

### ISSUE THREAD

**Issue by 0** [millermedeiros/vim-statline#19]
The other whitespace warnings are nice and short, but `[mixed-indenting]` takes up a bit of room. Could it be shortened to, e.g. `[mix]`?

**Comment by millermedeiros** [comment]
thx for the feedback, since my files usually don't have mixed indenting for too long (I do `:retab`) I end up not worrying about it.

I added an option to configure instead of changing the default value, but now I'm thinking I should also change the default value.

**Comment by 0** [comment]
This issue is really only a problem when working with someone else's code, where changing all the whitespace in a file isn't an option and the whitespace warnings are constantly present.
