### ISSUE TITLE
only displays in split windows

### ISSUE THREAD

**Issue by millermedeiros** [millermedeiros/vim-statline#3]
dominikgehl sent to me on twitter: In MacVim it only shows up in split windows … without the split, it's the basic status line. Any reason why ?  ([source](http://twitter.com/#!/dominikgehl/statuses/124871935917170688))

[gthank comment](http://twitter.com/#!/gthank/statuses/124870609481113600) also seems to be related.

strange thing is that I'm using MacVim.. maybe some conflict with other `statusline` settings or maybe the person doesn't have syntastic..

**Comment by kevincolyar** [comment]
Having the same issue.  Here's my vimrc: https://github.com/kevincolyar/vimfiles/blob/master/vimrc.erb.vim

I'm also using the terminal macvim(mvim) in a tmux session.

**Comment by dominikgehl** [comment]
Here's the Macvim version info:

:version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Sep 18 2011 16:00:17)
MacOS X (unix) version
Included patches: 1-315
Compiled by Bjorn Winckler bjorn.winckler@gmail.com
Huge version with MacVim GUI.  Features included (+) or not (-):
+arabic +autocmd +balloon_eval +browse ++builtin_terms +byte_offset +cindent +clientserver +clipboard +cmdline_compl
+cmdline_hist +cmdline_info +comments +conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con_gui +diff +digraphs +dnd
-ebcdic +emacs_tags +eval +ex_extra +extra_search +farsi +file_in_path +find_in_path +float +folding -footer +fork() +fullscreen
-gettext -hangul_input +iconv +insert_expand +jumplist +keymap +langmap +libcall +linebreak +lispindent +listcmds +localmap -lua
+menu +mksession +modify_fname +mouse +mouseshape +mouse_dec -mouse_gpm -mouse_jsbterm +mouse_netterm -mouse_sysmouse
+mouse_xterm +multi_byte +multi_lang -mzscheme +netbeans_intg +odbeditor +path_extra +perl +persistent_undo +postscript +printer
+profile +python -python3 +quickfix +reltime +rightleft +ruby +scrollbind +signs +smartindent -sniff +startuptime +statusline
-sun_workshop +syntax +tag_binary +tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title +toolbar
+transparency +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo +vreplace +wildignore +wildmenu +windows
+writebackup -X11 -xfontset +xim -xsmp -xterm_clipboard -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX -no-cpp-precomp
  -g -O2 -D_FORTIFY_SOURCE=1
Linking: gcc   -L.    -L.         -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon      -lncurses  -liconv -framework Co
coa    -fstack-protector -L/usr/local/lib  -L/System/Library/Perl/5.12/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -fram
ework Python   -framework Ruby

**Comment by dominikgehl** [comment]
.vimrc is simply

call pathogen#infect()
syntax enable
filetype plugin indent on

**Comment by faboo** [comment]
A vanilla Vim install will always display the status line with:
set laststatus=2

**Comment by dominikgehl** [comment]
Addind the set laststatus=2 line to my .vimrc solves the problem !

**Comment by kevincolyar** [comment]
Awesome, thanks!

**Comment by millermedeiros** [comment]
I had `laststatus=2` on my [.vimrc](https://gist.github.com/1262085) and totally forgot about it... added it to statline to avoid issues. thx!
