### ISSUE TITLE
Unknown Function SyntasticStatuslineFlag

### ISSUE THREAD

**Issue by daveray** [millermedeiros/vim-statline#6]
Maybe I'm being dumb, but on startup, I get two errors:

```
E117: Unknown function: SyntasticStatuslineFlag
E15: Invalid expression: SyntasticStatuslineFlag()
```

Interestingly, that symbol appears on statline.vim:70, but nowhere else.

Running VIM 7.3 on Ubuntu 11.04.

**Comment by millermedeiros** [comment]
you need to disable syntastic integration:

``` vim
" disable syntastic on the statusline
let g:statline_syntastic = 0
```

probably I should set it to false by default...

**Comment by daveray** [comment]
Got it. I should have read more carefully. Much better now.

I'd recommend leaving it on by default, but also check for the presence of syntastic. Thanks!
