### ISSUE TITLE
expand tab errors are not show

### ISSUE THREAD

**Issue by dominikgehl** [millermedeiros/vim-statline#8]
I have
set tabstop=8 softtabstop=8 shiftwidth=8 noexpandtab
in my .vimrc

Now, even when I manually indent a line with spaces, the statline doesn't show any expand tab errors

**Comment by millermedeiros** [comment]
I'm using `expandtab` and didn't noticed the problem.. I'm too used with Perl style regexp, negative lookahead for "*" (to avoid matching JavaDoc-style comments) was wrong. thx for reporting it.
